### ISSUE TITLE
Code signature invalid

### ISSUE THREAD

**Issue by ebaujard** [lvsti/CEF.swift#14]
Hi,
 I try to code sign CEFDemo with a developer ID.
On a macOS 10.11 no problem, but on 10.12 the app crash.

Error message :

Termination Reason: DYLD, [0x5] Code Signature

Dyld Error Message:
  Library not loaded: @rpath/CEFswift.framework/Versions/A/CEFswift
  Referenced from: /Users/USER/Desktop/*/CEFDemo.app/Contents/MacOS/CEFDemo
  Reason: no suitable image found.  Did find:
	
XXX/CEFDemo.app/Contents/MacOS/../Frameworks/CEFswift.framework/Versions/A/CEFswift: code signature invalid for 'XXX/CEFDemo.app/Contents/MacOS/../Frameworks/CEFswift.framework/Versions/A/CEFswift'

Binary Images:
       0x100e67000 -        0x100e71fff +xx.xxx.cef.demo (1.0 - 1) <2274C00E-C137-374F-93E3-A4B9410D9895> /Users/USER/Desktop/*/CEFDemo.app/Contents/MacOS/CEFDemo
       0x10dedd000 -        0x10df1adc7  dyld (433.5) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld

Have you ever tried to code sign this app ?

thanks

**Comment by lvsti** [comment]
I never tried codesigning the demo app before but now I gave it a try. First I didn't succeed because the embedded frameworks were indeed not signed. But after specifying 

```
OTHER_CODE_SIGN_FLAGS = "--deep";
```

for the CEFDemo target, everything worked like a charm. Let me know if this helped.

**Comment by ebaujard** [comment]
I also added this build option,  but when i launch the app on a another mac in 10.12 the app crash (with the previous error message). 
If i launch the app on the same mac where i build(in 10.12),  the app is launched without problems. 
When i launch the app on a another mac in  10.11 the app seems to work properly.

**Comment by lvsti** [comment]
I can get my hands on a second machine this weekend and check that scenario.

**Comment by xinlehou** [comment]
@ebaujard @lvsti 
I also encountered the same problem, I ask you to solve it

**Comment by lvsti** [comment]
Guys, no matter how hard I try, I cannot reproduce your issue. What does

```
$ codesign -vvvv /path/to/CEFDemo.app
```

output for you?
