### ISSUE TITLE
HTML5 video does not play in demo app

### ISSUE THREAD

**Issue by diederikh** [lvsti/CEF.swift#15]
When I load a web page with a `<video>` (e.g. loading the http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4 sample video) the video does not load and the framework gives the following error:

[0503/135638.460276:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: open context failed"}
[0503/135638.461050:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR demuxer: could not open

While the same HTML page plays in Chrome.

**Comment by lvsti** [comment]
Hi, which branch are you using? Could you try building and running the `cefsimple` or `cefclient` demo apps bundled with CEF (`cefsimple` target in `External/cef_binary/cef.xcodeproj`) and see if it can play the same video? The CEF.swift wrapper itself doesn't actually have a say whether something can be played or not, it just translates the APIs to swift.

**Comment by diederikh** [comment]
It turned out that CEF was not compiled with the right flags to include proprietary codecs (see http://www.chromium.org/audio-video). 
So `cefsimple` now shows the inline video but when I embed the same CEF framework inside the CEF.swift sample app then it does not work. It looks like `cefsimple` also links against libcef_lib libcef_dll_wrapper which I do not see in CEF.swift.

**Comment by lvsti** [comment]
Let me get this right, so you recompiled CEF yourself with the proprietary codecs and you tried to link that framework to the CEFDemo app, is that so? Can you give me a branch number and the exact build flags you used?

Btw, `libcef_dll_wrapper` has nothing to do with the video playback, it is just a mediator between C and C++ code, but CEF.swift doesn't use the C++ API.

**Comment by diederikh** [comment]
I did solve it eventually. The problem was that I copied the `cefsimple Helper` from the recompiled CEF instead of using the `setup.sh` from this repo. After doing this it worked fine.

If you're interested I used the following build flags/command to build ref with proprietary codecs:

`
#!/bin/bash
export CEF_USE_GN=1
export GN_DEFINES="is_official_build=true clang=true dcheck_always_on=true ffmpeg_branding=Chrome proprietary_codecs=true target_arch=x64"

python ../automate/automate-git.py --download-dir=/Users/diederik/Downloads/cefbuild/code/chromium_git --depot-tools-dir=/Users/diederik/Downloads/cefbuild/code/depot_tools --no-debug-build --x64-build --branch=3029 
`

**Comment by lvsti** [comment]
👍 good to know for future reference

**Comment by IdleJatt** [comment]
@diederikh can you please explain how to put the new CEF binary into project ? I am stuck in this from few hours basically I had successfully made new binary with following flags
**`ffmpeg_branding=Chrome`**
**`proprietary_codecs=true`**

When I replaced the **binary in External/cef_binary** with **new one** its throwing error that
**`error: install_name_tool: can't open file: External/cef_binary/Debug/Chromium Embedded Framework.framework/Chromium Embedded Framework (No such file or directory)`**

Its the structure of new binary
![image](https://user-images.githubusercontent.com/33171648/102471411-2fadb380-407b-11eb-9e2b-4ef4be9e2b95.png)
