### ISSUE TITLE
Unable to Read Post Data

### ISSUE THREAD

**Issue by Docgeo** [lvsti/CEF.swift#16]
Hi,

I try to read post data on a request (done by the web part). I see post data with the dev tools, but in the code, I have always the elements list empty (whereas elementCount = 1) :

```
if request.postData != nil && request.postData!.elementCount == 1{
            let elements = request.postData!.elements
            print ("----> element.count : \(elements!.count) ---- elementCount : \(request.postData!.elementCount)  ---  \(request.postData!.hasExcludedElements)" )
}

```
Trace : 
`----> element.count : 0 ---- elementCount : 1  ---  false`

Version used : 2924

Have you also the same problem ?

Thanks, regards

**Comment by Docgeo** [comment]
Found the solution :)

In CEFPostData.swift - row 40 :

```
/// Retrieve the post data elements.
    /// CEF name: `GetElements`
    public var elements: [CEFPOSTDataElement] {
        var count: size_t = 0
        var cefElements: UnsafeMutablePointer<cef_post_data_element_t>? = nil
        
        cefObject.get_elements(cefObjectPtr, &count, &cefElements)
```
As the count value is used in the method `get_elements`, it will always have 0 elements.The correction is simple (use the property elementCount, which have the good value) :

```
var count: size_t = elementCount
```

Thus the post data can be read without problem :)

I let you commit the correction, it will be easier.

**Comment by lvsti** [comment]
Thanks for surfacing this. The solution was actually a bit more involved as it turned out that `get_elements` wouldn't allocate any memory, so I had to fully construct `cefElements`. Pushing fix soon.

**Comment by lvsti** [comment]
Pls verify if it works for you as well

**Comment by Docgeo** [comment]
Hi,

Yes it works with your correction.
Without allocating memory, it was also working, but it was maybe luck.

So, I use now your correction, thanks.
