### ISSUE TITLE
Mac OS X 10.9 Support

### ISSUE THREAD

**Issue by Grodder** [lvsti/CEF.swift#18]
Hi,
I would like to use CEF.swift in a project, where I have to support Mac OS X 10.9.
Do you see any Issues with changing the deployment target of CEF.swift?
I tried to run the sample App on 10.9 and it worked fine.
The cef framework supports 10.9 as well.

**Comment by lvsti** [comment]
Hi, I should doublecheck but I also think there is no technical obstacle to that. Which branch are you using btw?

**Comment by Grodder** [comment]
Thanks, I'm using 2987.

**Comment by lvsti** [comment]
fixed in 74722ab7bbc4913bd3ea5f938fe5b8b31a3a6fe2
