### ISSUE TITLE
Support for HTML5 Video

### ISSUE THREAD

**Issue by sheenvempeny** [lvsti/CEF.swift#20]
Hi,

Please add the support for HTML5 Video.

Regards,
Sheen

**Comment by lvsti** [comment]
Please read https://github.com/lvsti/CEF.swift/issues/15 to see if it solves your problem. If not, please provide a more detailed description of what exactly you are expecting to work but is not.

**Comment by sheenvempeny** [comment]
Thank you. I fixed it.
