### ISSUE TITLE
 CEFDemo outdated

### ISSUE THREAD

**Issue by doizece** [lvsti/CEF.swift#21]
func doClose(browser: CEFBrowser) -> Bool   to be replaced with

func onDoClose(browser: CEFBrowser) -> CEFOnDoCloseAction {
...
return  CEFOnDoCloseAction.allow
}

**Comment by doizece** [comment]
Though, in this particular example, it doesn't matter.

**Comment by lvsti** [comment]
thanks for spotting it, fixed it for branch 3202

**Comment by doizece** [comment]
btw, I don't manage to have  onBeforeClose(browser: CEFBrowser) called after windowShouldClose(_ sender: NSWindow) returns true. (browser's  view being child of a view in the main window of the app in my case). Can you help me with a suggestion, please?

**Comment by doizece** [comment]
In CEFDemo, in createApplication(), Bundle stuff creates an unnecessary extra-window)

**Comment by doizece** [comment]
And maybe: 

func closeAllBrowsersLean() {
        if !CEFTaskUtils.isCurrentlyOnThread(threadID: .ui) {
            CEFTaskUtils.postTaskOnThread(threadID: .ui, block: closeAllBrowsersLean)     
        }
        _browserList.forEach { browser in
            browser.host?.closeBrowser(force: false)
        }
}

**Comment by doizece** [comment]
Is that cef_application_mac_capi.h file really needed?

**Comment by lvsti** [comment]
well so far I have been trying to keep the codebase free from AppKit (using Foundation only), but since the CEF framework already links against pretty much all the application frameworks (AppKit included), I guess I could move that file as well into the swift package

**Comment by doizece** [comment]
I see, only UnderlayOpenGLHostingWindow : NSWindow, otherwise CefAppProtocol is AppKit agnostic.  There is a cef_application_mac.h in include, sadly c++.  Btw, can the pthread stuff in CEFBase.swift be replaced by atomic ops?  (Like in atomic_ref_count.h from Chromium.)

**Comment by doizece** [comment]
After all, CEF.swift is for macOS only. I think is more about abandoning "pure swift" strategy.

**Comment by doizece** [comment]
What about creating CEFDemo Helper in swift (as a dependency target)?

**Comment by lvsti** [comment]
Makes sense, I've made some progress on it but got stuck with some module import issues. ETA probably this weekend.

**Comment by doizece** [comment]
It would be nice.  A Library dir with CEF.framework and CEF.swift.framework must be all it takes.

**Comment by lvsti** [comment]
Check out the 3202 branch which now has a `CEFApplication` class that wraps the common required functionality for event dispatch, and also a `CEFDemo Helper (Swift)` target in the sample project which makes it unnecessary to build the sample helpers in the CEF binary distribution. There is one caveat: if you implement the helper app in Swift, it gets packaged with the Swift standard libraries which means an additional 11 MB in the binary size. If you don’t do anything special in the render process, I recommend using the `CEFDemo Helper (C)` target which does the exact same thing, just in 10 KB. :)

**Comment by doizece** [comment]
Elegant!

**Comment by doizece** [comment]
Things in cef_application_mac_capi.h can be absorbed in CEFApplication.swift, can't they?

**Comment by doizece** [comment]
Agree, CEFDemo Helper (Swift) is currently worthless (and keeping it alongside (C) target is rather confusing ). Getting rid of that duplicate Swift runtime... hm.. maybe it will disappear in the future by itself.

**Comment by doizece** [comment]
I use 10.13, why not ?

**Comment by lvsti** [comment]
ok so can we close this issue now?

**Comment by doizece** [comment]
cef_application_mac_capi.h  not needed at all. CEFDemo.xcodeproj needs some tweaks.
It's up to you.

**Comment by lvsti** [comment]
1. You use 10.13 but others might not. There is no harm in having 10.9 as the deployment target
2. Which lines do you think are not needed in `cef_application_mac_capi.h`? `CefAppProtocol` conformance is a must for any NSApplication subclass to work properly with CEF

**Comment by doizece** [comment]
1. Ok. Just saying.
2. May be this works...

```swift
@objc protocol CrAppProtocol {
    func isHandlingSendEvent() -> Bool
}

@objc protocol CrAppControlProtocol: CrAppProtocol {
    func setHandlingSendEvent( handlingSendEvent: Bool)
}

protocol CefAppProtocol: CrAppControlProtocol {
}

class UnderlayOpenGLHostingWindow : NSWindow {
}
```
 in CEFApplication.swift. No more cef_application_mac_capi.h, (and no more cp it to include dir).

**Comment by doizece** [comment]
think the issue might be closed. good luck.

**Comment by lvsti** [comment]
I didn't think of that but it actually makes sense for the protocols. As for `UnderlayOpenGLHostingWindow`, Swift doesn't support forward declarations but I can sneak it into the framework header so I can eventually skip the `cef_application_mac_capi.h` hack. Thanks for the suggestion.

**Comment by lvsti** [comment]
btw I have a PR for CEF (https://bitbucket.org/chromiumembedded/cef/pull-requests/129) that will make it possible to include the `cef_application_mac.h` in the module, which will make the above workaround unnecessary.

**Comment by doizece** [comment]
UnderlayOpenGLHostingWindow's implementation does nothing (but checks in init that window's  rect is not zero). It's there only because in the past did more.

**Comment by doizece** [comment]
Even better. 

p.s. To complete the workaround:
UnderlayOpenGLHostingWindow's implementation does nothing but checks in init that window's contentRect it's not zero width or height.  Not being exposed elsewhere, I presume it can be neglected. Or easily reimplemented in CEFApplication.swift.

**Comment by doizece** [comment]
I think CEFDemo looks better now; can we close this issue?

**Comment by lvsti** [comment]
How UnderlayOpenGLHostingWindow works and what it does is an implementation detail that CEF.swift should not know/care about. If the framework states that browser windows should inherit from it, CEF.swift should make that possible, even if the class is just an empty subclass. So I'm leaving it there for now.
