### ISSUE TITLE
onBeforeClose not called?

### ISSUE THREAD

**Issue by doizece** [lvsti/CEF.swift#22]
I don't manage to have CEFLifeSpanHandler.onBeforeClose(browser: CEFBrowser) triggered after windowShouldClose(_ sender: NSWindow) returns true and  the window is destroyed. (browser's view being child of a view in the window of the app in my test sample, i.e. the window is not created by  CEF)

**Comment by lvsti** [comment]
from the header comments of `DoClose`:

> Called when a browser has recieved a request to close. This may result directly from a call to `CefBrowserHost::CloseBrowser()` or indirectly if the browser is parented to a top-level window created by CEF and the user attempts to close that window (by clicking the 'X', for example).

To me this means that if you want to receive `onDoClose` you either have to have the browser in a CEF-managed window or call `CEFBrowserHost.closeBrowser()` manually

**Comment by doizece** [comment]
It's something like this pseudo: isClosing = false; windowShouldClose { if ! isClosing CloseBrowser return false else return true} ;   onDoClose{ isClosing=true; return .allowed} . So, CloseBrowser makes onDoClose to be called; this one returning .allowed will send a performClose to the windows which results in another call to windowShouldClose. This time,   windowShouldClose returns true and the window is closed. Ok. But, from DoClose docs: " 9. Application's top-level window is destroyed. 10. Application's OnBeforeClose() handler is called and the browser object is destroyed. 11. Application exits by calling CefQuitMessageLoop() if no other browsers exist."
Sadly, no OnBeforeClose appeared.

**Comment by doizece** [comment]
My fault.  onBeforeClose won't be triggered  if client.browser.host.windowHandle.removeFromSuperview() is not called (from windowShouldClose), even if .allowed by onDoClose.
