### ISSUE TITLE
Atomic ref count

### ISSUE THREAD

**Issue by doizece** [lvsti/CEF.swift#23]
While pthread works, using atomics would be better.(not an issue but a todo)

**Comment by lvsti** [comment]
you mean like this? https://github.com/lvsti/CEF.swift/pull/25

**Comment by doizece** [comment]
More like  atomic_ref_count.h from Chromium  or  cef_atomicops_x86_gcc.h from CEF/Linux since cef_atomicops_mac.h deprecated (in 10.13 at least).

**Comment by lvsti** [comment]
what difference would that make compared to the OS-provided locking mechanisms?

**Comment by doizece** [comment]
... or <stdatomic.h> of C11. (Sorry, stupid me)
Simpler, faster.  No need to lock/block, no sys calls.
.

**Comment by doizece** [comment]
add_ref, release and has_one_ref from cef_base_ref_counted_t  to be implemented directly in C  using <stdatomic.h>. Just a suggestion.

**Comment by lvsti** [comment]
if you refer to the refcounting in `CEFMarshaller` then I'm afraid it has to be locking since it's not just about testing and changing a number but also setting/releasing the reference to `self`. But if you have a solution, feel free to submit a PR.

**Comment by doizece** [comment]
You're right. I didn't realised that.
