### ISSUE TITLE
bundle format unrecognized, invalid, or unsuitable In subcomponent:

### ISSUE THREAD

**Issue by Vactorwang** [lvsti/CEF.swift#31]
I've import CEFswift.framework. But when i build for Mac app,it said /MacGate.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /MacGate.app/Contents/Frameworks/Versions/A/Modules/CEFswift.swiftmodule

**Comment by lvsti** [comment]
From the path you showed it looks like that you somehow copied only the internals of the CEFswift.framework, not the framework itself. Inside your MacGate.app the path should look like this:

```
MacGate.app/Contents/Frameworks/CEFswift.framework/Versions/A/...
```

**Comment by Vactorwang** [comment]
https://git.coding.net/vactorwang/macgate.git  It's my demo , anything wrong?

**Comment by WarWithinMe** [comment]
Also notice that currently `Chromium Embedded Framework.framework` structure is different from other bundle. You have to manually make its structure the same as other bundle, otherwise `codesign` will complain
