### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by wasi166** [lvsti/CEF.swift#35]
Building external dependencies
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command /bin/sh failed with exit code 128

**Comment by lvsti** [comment]
I'm assuming you are trying to build the project manually. If that is the case, you must switch to the branch that matches the CEF branch you are interested in. See the README for details.

**Comment by lvsti** [comment]
did it help? can I close this issue?

**Comment by wasi166** [comment]
no
when I use carthage , it shows "failed to build the project" in terminal
so I am doing it manually , I am cloning cef_3359 branch
