### ISSUE TITLE
Error from Carthage

### ISSUE THREAD

**Issue by wasi166** [lvsti/CEF.swift#36]
*** Checking out CEF.swift at "33591af94c07ce8849611e0eb63628cb2940f2a3"
*** xcodebuild output can be found in /var/folders/ff/n72h5rqx61lcsld8xyq60n640000gn/T/carthage-xcodebuild.1rC86w.log
*** Building scheme "CEF.swift" in CEF.swift.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/vozyesmc/Documents/Cef\ test/Carthage/Checkouts/CEF.swift/CEF.swift.xcodeproj -scheme CEF.swift -configuration Release -derivedDataPath /Users/vozyesmc/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/CEF.swift/33591af94c07ce8849611e0eb63628cb2940f2a3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/ff/n72h5rqx61lcsld8xyq60n640000gn/T/CEF.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/vozyesmc/Documents/Cef test/Carthage/Checkouts/CEF.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/ff/n72h5rqx61lcsld8xyq60n640000gn/T/carthage-xcodebuild.1rC86w.log

**Comment by wasi166** [comment]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/vozyesmc/Documents/Cef\ test/Carthage/Checkouts/CEF.swift/CEF.swift.xcodeproj -scheme CEF.swift -configuration Release -derivedDataPath /Users/vozyesmc/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/CEF.swift/06d64a84fba1e93233dbac55abf4a7e826141ac5 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/ff/n72h5rqx61lcsld8xyq60n640000gn/T/CEF.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/vozyesmc/Documents/Cef test/Carthage/Checkouts/CEF.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/ff/n72h5rqx61lcsld8xyq60n640000gn/T/carthage-xcodebuild.xVrKnW.log


here we go , getting the same error with different error log

and when I tried to build manually in carthage checkouts folder then I got following message. please help its really urgent.

Building external dependencies
fatal: Not a git repository (or any of the parent directories): .git
Command /bin/sh failed with exit code 128

**Comment by lvsti** [comment]
you should check the contents of the xcodebuild log that the carthage error message mentions, maybe it gives you a clue
