### ISSUE TITLE
How to turn on Widevine?

### ISSUE THREAD

**Issue by junetou** [lvsti/CEF.swift#39]
I want to know how to open Widevine, I called registerWidevineCDM before initializeMain and returned CEF_CDM_REGISTRATION_ERROR_NONE, but when I tested it at https://bitmovin.com/demos/drm it showed that Widevine is not turned on, I need some help, thank you very much.

**Comment by lvsti** [comment]
which branch are you using?

**Comment by junetou** [comment]
Thank you for your reply. System Version:MacOS 10.14.4. Xcode Version:10.2.1. Branch:cef_3770. And I used CEFDemo Helper (C) (CEFDemo) Target Dependencies to compile CEFDemo. @lvsti

**Comment by lvsti** [comment]
Did you try it with the CEF sample app? I'm referring to the one shipped with CEF (checked out at `External/cef_binary/tests/cefclient`)

**Comment by junetou** [comment]
Sample app can't use Widevine, I always thought that the sample app can use widevine, I am very sorry. Do you know if there is any way to make the Sample App use widevine too? Thank you very much.

**Comment by lvsti** [comment]
I have no idea but you can ask on the [CEF forum](https://magpcss.org/ceforum/)
