### ISSUE TITLE
AAC support

### ISSUE THREAD

**Issue by Vactorwang** [lvsti/CEF.swift#40]
what can I do to support AAC and H.264

**Comment by lvsti** [comment]
CEF.swift is just a language wrapper over CEF, which by default doesn't ship with proprietary codecs because of licensing reasons. You'll need to make a custom build with those codecs enabled, see [the CEF forum](https://magpcss.org/ceforum/viewtopic.php?f=6&t=17038) for instructions.

**Comment by Vactorwang** [comment]
Thank you very much , I got it
