### ISSUE TITLE
Crashes when trying to do offscreen rendering. Plus CEFDemo too

### ISSUE THREAD

**Issue by knightbenax** [lvsti/CEF.swift#47]
Currently if you try to use windowless rendering, you get a crash at the runMessageLoop() function. The error message isn't quite clear

**Comment by knightbenax** [comment]
Resolved this. Putting here for anyone from the future. You need to provide the `viewRectForBrowser` as well as `onPaint` methods in a custom CEFRenderHandler and you should be good to go

**Comment by lvsti** [comment]
Can you tell me whether it was a crash in CEF.swift or in CEF itself?

**Comment by knightbenax** [comment]
It's an error itself with CEF. Turns out if you don't provide the GetViewRect, CEF doesn't know what bounds to draw the off-screen window at. 

The CEF docs just didn't say that.
