### ISSUE TITLE
How to build CEFDemo? Got build error... 

### ISSUE THREAD

**Issue by jerrychen44** [lvsti/CEF.swift#50]
Xcode build error for CEFDemo (Xcode 12.0, Macos 10.15.6)
Log:
SwiftHelper
    CEFDemo/main.swift:10:8: No such module 'CEFswift'

CEFDemo Helper (GPU)
    library not found for -lCEFSandbox

Step I did.
1.git clone this project (Nov092020), switch to cef_4240, build pass CEF.swift from setup.sh in the command line.
2.build pass from CEF.swift Xcode project and got CEFswift.framework, libCEFSandbox.a in the products folder.
3.cd to the CEFDemo project folder, double click to open the CEFDemo Xcode project file, simply press build for CEFDemo.

Did I miss some steps to include the CEFswift and libCEFSandbox for the CEFDemo.app project on Xcode?
Thank you so much.

**Comment by lvsti** [comment]
Hello,

the CEFDemo project is configured to look for the Release artifacts from the CEF.swift build. So when you open the CEF.swift project, you need to switch to the Release configuration before building. 

Hope this helps.

**Comment by lvsti** [comment]
I also found that there was a code signing issue when building CEFDemo, so I fixed that on cef_4240

**Comment by jerrychen44** [comment]
Hi, Sir.
Thanks for your reply.
For my case, I already switch the branch of CEF.swift to cef_4240 and build successfully the CEF.swift first.
Then I open the CEFDemo Xcode project under the samples folder and built failed from Xcode ide.

From your reply, seems that I don't have to do anything and the CEFDemo can build pass directly. 
(Because I already built CEF.swift under cef_4240)
Am I right? or Even the CEFDemo project need to switch to cef_4240 branch?
Thanks.

**Comment by lvsti** [comment]
Absolutely, the CEFDemo is kept up-to-date with the CEF.swift framework, so if you build the FW from cef_4240 then you should use the sample of the same branch. The master branch is useless for any development.

**Comment by jerrychen44** [comment]
Got it, thanks.
