### ISSUE TITLE
Can CEF.swift be embedded in UIKit/SwiftUI?

### ISSUE THREAD

**Issue by kchair** [lvsti/CEF.swift#51]
Hello, is it possible to embed CEF.swift in a UIKit/SwiftUI app? I looked at the demo code, but it looks like CEF creates its own window. I'm wondering if this can be a drop-in replacement for WKWebView. Thanks

**Comment by kchair** [comment]
looks like i was able to get what i need with `winInfo.setAsChild`

**Comment by umairzahid508** [comment]
Did you @kchair figure out how to embed it ?
