### ISSUE TITLE
Build CEF binary with flags

### ISSUE THREAD

**Issue by IdleJatt** [lvsti/CEF.swift#53]
@diederikh can you please explain how to put the new CEF binary into project ? I am stuck in this from few hours basically I had successfully made new binary with following flags
**`ffmpeg_branding=Chrome`**
**`proprietary_codecs=true`**

When I replaced the **binary in External/cef_binary** with **new one** its throwing error that
**`error: install_name_tool: can't open file: External/cef_binary/Debug/Chromium Embedded Framework.framework/Chromium Embedded Framework (No such file or directory)`**

Its the structure of new binary
![image](https://user-images.githubusercontent.com/33171648/102471411-2fadb380-407b-11eb-9e2b-4ef4be9e2b95.png)

_Originally posted by @IdleJatt in https://github.com/lvsti/CEF.swift/issues/15#issuecomment-747332191_

**Comment by lvsti** [comment]
Haven't tried it myself, but as I see, the error message says that the framework is not found, and indeed in your directory listing there is no Debug and Release folder. I'd begin with that.
