### ISSUE TITLE
CEFSwift framework compiling issue in another project.

### ISSUE THREAD

**Issue by umairzahid508** [lvsti/CEF.swift#63]
When I use CEFswift framework in my own project it has given some error which I showed in the below picture .

![image](https://user-images.githubusercontent.com/18383380/138326469-a0e23e14-ce82-45aa-b986-3f82ef4fe782.png)

I really need to add this framework in my project so I can build the product for my own.

**Comment by lvsti** [comment]
If you want to integrate CEF.swift into your build, you have to make sure the Chromium headers are available as well.
